services:
  storage:
    restart: always
    image: minio/minio
    ports:
      - ${S3_PORT:-9000}:9000
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY:-minio}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY:-minio124}
    command: server /data
    volumes:
      - .docker/volumes/storage:/data
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --collation-server=utf8mb4_unicode_ci
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MYSQL_DATABASE:-tc-db}
      MYSQL_USER: ${MYSQL_USER:-dbuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dbpassword}
    volumes:
      - mysql:/var/lib/mysql

  db-ui:
    image: adminer
    depends_on:
      - mysql
    ports:
      - ${ADMINER_PORT:-8888}:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=dracula

volumes:
  mysql:
